/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminosRouteImport } from './routes/terminos'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as FormRouteImport } from './routes/form'
import { Route as EssentialRouteImport } from './routes/essential'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicSendContactRouteImport } from './routes/api/public/send-contact'
import { Route as ApiPublicCreateVideoUploadRouteImport } from './routes/api/public/create-video-upload'

const TerminosRoute = TerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const FormRoute = FormRouteImport.update({
  id: '/form',
  path: '/form',
  getParentRoute: () => rootRouteImport,
} as any)
const EssentialRoute = EssentialRouteImport.update({
  id: '/essential',
  path: '/essential',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSendContactRoute = ApiPublicSendContactRouteImport.update({
  id: '/api/public/send-contact',
  path: '/api/public/send-contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCreateVideoUploadRoute =
  ApiPublicCreateVideoUploadRouteImport.update({
    id: '/api/public/create-video-upload',
    path: '/api/public/create-video-upload',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/essential': typeof EssentialRoute
  '/form': typeof FormRoute
  '/premium': typeof PremiumRoute
  '/privacidad': typeof PrivacidadRoute
  '/terminos': typeof TerminosRoute
  '/api/public/create-video-upload': typeof ApiPublicCreateVideoUploadRoute
  '/api/public/send-contact': typeof ApiPublicSendContactRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/essential': typeof EssentialRoute
  '/form': typeof FormRoute
  '/premium': typeof PremiumRoute
  '/privacidad': typeof PrivacidadRoute
  '/terminos': typeof TerminosRoute
  '/api/public/create-video-upload': typeof ApiPublicCreateVideoUploadRoute
  '/api/public/send-contact': typeof ApiPublicSendContactRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/essential': typeof EssentialRoute
  '/form': typeof FormRoute
  '/premium': typeof PremiumRoute
  '/privacidad': typeof PrivacidadRoute
  '/terminos': typeof TerminosRoute
  '/api/public/create-video-upload': typeof ApiPublicCreateVideoUploadRoute
  '/api/public/send-contact': typeof ApiPublicSendContactRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cookies'
    | '/essential'
    | '/form'
    | '/premium'
    | '/privacidad'
    | '/terminos'
    | '/api/public/create-video-upload'
    | '/api/public/send-contact'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cookies'
    | '/essential'
    | '/form'
    | '/premium'
    | '/privacidad'
    | '/terminos'
    | '/api/public/create-video-upload'
    | '/api/public/send-contact'
  id:
    | '__root__'
    | '/'
    | '/cookies'
    | '/essential'
    | '/form'
    | '/premium'
    | '/privacidad'
    | '/terminos'
    | '/api/public/create-video-upload'
    | '/api/public/send-contact'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CookiesRoute: typeof CookiesRoute
  EssentialRoute: typeof EssentialRoute
  FormRoute: typeof FormRoute
  PremiumRoute: typeof PremiumRoute
  PrivacidadRoute: typeof PrivacidadRoute
  TerminosRoute: typeof TerminosRoute
  ApiPublicCreateVideoUploadRoute: typeof ApiPublicCreateVideoUploadRoute
  ApiPublicSendContactRoute: typeof ApiPublicSendContactRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terminos': {
      id: '/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof TerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/form': {
      id: '/form'
      path: '/form'
      fullPath: '/form'
      preLoaderRoute: typeof FormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/essential': {
      id: '/essential'
      path: '/essential'
      fullPath: '/essential'
      preLoaderRoute: typeof EssentialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/send-contact': {
      id: '/api/public/send-contact'
      path: '/api/public/send-contact'
      fullPath: '/api/public/send-contact'
      preLoaderRoute: typeof ApiPublicSendContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/create-video-upload': {
      id: '/api/public/create-video-upload'
      path: '/api/public/create-video-upload'
      fullPath: '/api/public/create-video-upload'
      preLoaderRoute: typeof ApiPublicCreateVideoUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CookiesRoute: CookiesRoute,
  EssentialRoute: EssentialRoute,
  FormRoute: FormRoute,
  PremiumRoute: PremiumRoute,
  PrivacidadRoute: PrivacidadRoute,
  TerminosRoute: TerminosRoute,
  ApiPublicCreateVideoUploadRoute: ApiPublicCreateVideoUploadRoute,
  ApiPublicSendContactRoute: ApiPublicSendContactRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
